### ISSUE TITLE
Code after stream will never be called

### ISSUE THREAD

**Issue by normpad** [cystic/IOTA-Faucet-Bot#1]
https://github.com/cystic/IOTA-Faucet-Bot/blob/ab400ab6f05884ab941e9c0e91787180fc6c65e7/if.py#L28

subreddit.stream.submissions() will continuously yield comments as they become available. As it is essentially an infinite loop any code after it will never be called. You need to write to the database inside the loop after each reply.

**Comment by nicoschtein** [comment]
Check #2

**Comment by nicoschtein** [comment]
#2 fixed this issue.
