### ISSUE TITLE
Post identifiers aren't saved on new line.

### ISSUE THREAD

**Issue by cystic** [cystic/IOTA-Faucet-Bot#3]
Pody identifiers are all grouped together in a single block of text making the bot reply to the same posts over again when it reruns.

Instead of this:
6zb436
6zbq9m
6zbqsg
6zbwz8
6zcgw9
6zce62
6zcdu7
6zc3bh
6zc31q

It looks like this: 70dr8270e0dj70e3a470e9a770ede270ehdw70emdp70emqm70eo0870eu8z70f4gz70f6z670fcsu70fgt270fhsp70fi3q70fi4b70fi5c70fkq570fr6470frs170g7gf70ggv470gh2270ghtf70gi6i70gmf870gojs70gqdr70gqop70gtbg70gzqu70hf0i70hy0u70i70k70icjp70iee370iewa70igyy70iiuo70irbm70iw0a70j17u70j6jw70jae570jbuz70je7p70jj0l70jp7m70jw1870knpq70kqgq70kw9q70l3ry70l4z170lava70lpfh70lrkt70m0d270m27l70m9w370mefw70mfmi70mhcw70mp1n70mstk70msw370n2i470n5w870n6if70ni2570nmw270nx6270oa4j70onzp70p2fc70ppsw70pt6370puef70pwek70qbym70qnkf70qp0970qrgp70qt5670qxj470r77770r8xk70reuq70rew270rews70rm4l70rqxw70ruhg70rumg70s0cr70shuo70skt270sme270sxmd70t9kg70tbfp70tcjr70temm70tj6p70tkit70tlwq70tn7u70to0070toof70tpz670tqdy70tr5y70tr8y70tvpt70txc670tyr670u0v570u4gt70u60g70u60q70u7ck70uapl70udp770ue0570ueju70uhuk70um3g70uqg470urcx70v23670v3uw70v74x70v9o570v9oi70vahi70vcb170vepm70veqw70veru70vl0470vnx670vnyl70vvox70vw3m70w2bk70w2l170wbdz70mstk70msw370n2i470n5w870n6if70ni2570nmw270nx6270oa4j70onzp70p2fc70ppsw70pt6370puef70pwek70qbym70qnkf70qp0970qrgp70qt5670qxj470r77770r8xk70reuq70rew270rews70rm4l70rqxw70ruhg70rumg70s0cr70shuo70skt270sme270sxmd70t9kg70tbfp70tcjr70temm70tj6p70tkit70tlwq70tn7u70to0070toof70tpz670tqdy70tr5y70tr8y70tvpt70txc670tyr670u0v570u4gt70u60g70u60q70u7ck70uapl70udp770ue0570ueju70uhuk70um3g70uqg470urcx70v23670v3uw70v74x70v9oi70vahi70vcb170vepm70veqw70veru70vl0470vnx670vnyl70vvox70vw3m70w2bk70w2l170wbdz70wldh70wm0s70wxv070wydo70x0h070x2gp70x38t70x39270x3je70xdmw70xhor70xkh770xv1j70y2be70y4yy70y6l970ybkw70yc4i70ydlr70ydmf70ydn1

**Comment by normpad** [comment]
Try changing the last line to 

`f.write('\n' + submission.id)`

or 

`f.write(submission.id + '\n')`

might be better

**Comment by cystic** [comment]
Thank you! I am trying the first one and seeing how it goes now. I think that should do it.

**Comment by cystic** [comment]
Tested and working like a champ! Thank you! Going to close this issue and commit the code on Github now.
